apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payflow
labels:
  - pairs:
      app.kubernetes.io/part-of: payflow
    includeSelectors: false
resources:
  - prometheus/configmap-rules.yaml
  - grafana/configmap-dashboard.yaml
