apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payflow-api
  labels:
    app.kubernetes.io/name: payflow-api
    app.kubernetes.io/part-of: payflow
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payflow-api
